version: '3'

services:
  ## Database container
  mongodb:
    image: mongo:4.4
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped

  trustroots:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: production.Dockerfile
    volumes:
      - ./local.js:/home/app/trustroots/config/env/local.js
    depends_on:
      - mongodb
    ports:
      - '3000:80'
