version: '3'

networks:
  trustroots-network:
    driver: bridge

volumes:
  node-modules:
  public:
  dbdata:

services:
  trustroots:
    image: node:14
    container_name: trustroots
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # Mount the app dir in the container so our changes
    #  to the app code are also changed in the container
    #
    # Mount node_modules separately as a data volume, so
    #  that they won't get overwritten by app directory
    #  Read more: http://stackoverflow.com/a/32785014/1984644
    networks:
      - trustroots-network
    volumes:
      - ./:/trustroots
      - node-modules:/trustroots/node_modules
      - public:/trustroots/public
    depends_on:
      - mongodb
    ports:
      - '1080:1080'
      - '3000:3000'
      - '3001:3001'
      - '5858:5858'
      - '35729:35729'
    environment:
      - DB_1_PORT_27017_TCP_ADDR=mongodb

  ## Database container
  mongodb:
    image: mongo:4.4
    container_name: db_1
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - trustroots-network
