name: Extract new translation strings

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Extract strings
        run: |
          npm run i18n:extract
          git status
      - name: Reformat plural strings for Weblate
        run: |
          npm run i18n:fix-weblate
          git status
      - name: Commit changes
        # We only add the Englsih strings, as that is the source language, and Weblate effectively owns the others
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git status
          git add ./public/locales/en/*.json
          if ! git diff --staged --exit-code -- ./public/locales >/dev/null; then
            git commit -m 'Extract locales'
            git push github HEAD:${GITHUB_REF} --quiet
          fi
